spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: koicaresystem@koi-care-system
    url: jdbc:sqlserver://koi-care-system.database.windows.net:1433;database=koicaresystemdatabase;user=koicaresystem@koi-care-system;password=Application123;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    password: Application123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: storephuoc@gmail.com
    password: ncux oxqc ldqu leih
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  cloud:
    azure:
      storage:
        account-name: koicaresystem
        account-key: 175TMuZQZ9MwEgVLezP1JPCGZrTK5WFev9/u4pgZ32cywkpMJb+78mxVc9+iU//4MtJcUVS3ey5u+AStaPeOMw==
  servlet:
    multipart:
      enabled: true
      max-request-size: 20MB
      max-file-size: 2MB
