server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
jwt:
  signerKey: "1Xt6QiR02nO30C3YVxkkG/qxQQ9sECaUY44pi2Do2SgF/OACYM7RKc/M+ED95TsX"
payment:
  vnPay:
    url: ${VN_PAY_URL}
    tmnCode: ${VN_PAY_TMN_CODE}
    secretKey: ${VN_PAY_SECRET_KEY}
    returnUrl: http://localhost:8080/api/payment/vn-pay-callback
    version: "2.1.0"
    command: "pay"
    orderType: other
